- .github/workflows/ci.yml
- README.md
- version.php
- docs: add branches table and installation instructions
- ci: add reusable workflows and set a fixed supported range
> add some required plugin details

- classes/task/process_workflows.php
- classes/visualiser.php
- db/install.xml
- db/tasks.php
- db/upgrade.php
- visual.php
WIP:
Will need to store and load the dataflow configurations to render an actual workflow, but this will render the example below for now.
> feat: add base handling to render a workflow graph in dot

- classes/dataflow.php
- classes/graph.php
- classes/step.php
- classes/step/base_step.php
- classes/step/debugging.php
- classes/step/join.php
- classes/step/mtrace.php
- classes/step/void_step.php
- classes/step_form.php
- db/install.xml
- edit.php
- lang/en/tool_dataflows.php
- lib.php
- step.php
- tests/tool_dataflows_test.php
- version.php
- db: add foreign key and step uniqueness constraint on name and flowid
- fix: deps handling for new steps, tidied form and add title / headings
- add input & output stream counts to base class, and add join step type
- test: add dataflow is_dag check and supporting tests
Related to #25
> 25 add step validation

- classes/privacy/provider.php
- lang/en/tool_dataflows.php
This should resolve CI issues.
Resolves #56
> fix: add updated privacy api implementation based on current db fields

- classes/dataflow.php
- classes/dataflow_form.php
- classes/dataflows_table.php
- classes/execution/engine.php
- classes/parser.php
- classes/step.php
- classes/step_form.php
- classes/steps_table.php
- db/install.xml
- lang/en/tool_dataflows.php
- step.php
- tests/fixtures/sample-with-expressions.yml
- tests/tool_dataflows_test.php
- version.php
- fix: add check to ensure invalid dependson value will throw an exception
- feat: add tests and support for expressions & config changes
- feat: add support for updating the dataflow config in the UI
- refactor: change usage of internalid to use the word 'alias' instead
> 5 expressions and var scopes

- classes/visualiser.php
- edit.php
- index.php
- settings.php
- step.php
- steps.php
- refactor: move overview.php to index.php
- feat: add breadcrumb navigation to list/info/edit pages
> move and fix page breadcrumb navigation

- classes/dataflows_table.php
- classes/visualiser.php
- lang/en/tool_dataflows.php
- run.php
- feat: add ability to run a dataflow manually
- fix: changed dataflow run now button into icon in the table
Resolves #83
> add run dataflow now

- run.php
> Issue #99: Replace require_admin()

- classes/dataflow.php
- classes/dataflow_form.php
- classes/dataflows_table.php
- classes/execution/engine_step.php
- classes/exportable.php
- classes/import_form.php
- classes/step.php
- classes/step_form.php
- classes/visualiser.php
- export.php
- import.php
- lang/en/tool_dataflows.php
- tests/fixtures/sample-export.yml
- tests/tool_dataflows_test.php
Resolves #4 
Resolves #82 
Resolves #80 because the download options are no longer present.
Note: This does NOT include functionality to import/export individual steps, however the capability to do so is there. Just needs a way to wire it up and call it from the UI.
> feat: add functionality to export/import a dataflow + supporting tests

- classes/dataflow.php
- tests/tool_dataflows_test.php
> fix: steps listing which was not returning detached nodes with tests

- classes/execution/engine.php
- classes/execution/engine_step.php
- classes/execution/iterators/map_iterator.php
- classes/execution/iterators/php_iterator.php
- lang/en/tool_dataflows.php
- tests/execution/tool_dataflows_engine_test.php
Add debug statements to the engine execution, and on iterator steps.
I specifically request comments about the extensiveness of debugging, and how to determine if debugging will occur.
OK to squash.
> Issue #27: Debugging

- classes/dataflow.php
- classes/step.php
- classes/steps_table.php
- lang/en/tool_dataflows.php
- remove-step.php
- tests/application_trait.php
- tests/tool_dataflows_test.php
- feat: add ability to remove a step with supporting tests
- feat: add web ui for step deletion
Resolves #85 
Related to #106  - should cover the MVP.
> 85 add step deletion

- classes/dataflows_table.php
- classes/step/sql_reader.php
- classes/visualiser.php
- edit.php
- remove-step.php
- run.php
- step.php
- tests/execution/tool_dataflows_engine_test.php
- view.php
- refactor: move steps.php to view.php as it displays dataflow details
- fix: run now behaviour for exceptions and nav links
- fix: dataflow edit page nav hierarchy
Resolves #109
Resolves #110 
Resolves #125 
Resolves #129
> restructure pages and correct nav

- classes/step.php
> fix: issue where the last dependency for a step could not be removed

- db/access.php
- lang/en/tool_dataflows.php
> fix: add missing lang strings for capabilities

- classes/dataflow.php
> fix: output stream validation overriding input validation due to typo

- import.php
> fix: import now tracks the user adding the dataflow

- classes/execution/iterators/map_iterator.php
- classes/formats/encoder_base.php
- classes/formats/encoders/csv.php
- classes/formats/encoders/json.php
- classes/step/stream_writer.php
- lang/en/tool_dataflows.php
- lib.php
- tests/tool_dataflows_stream_writer_test.php
Add encoders for json and csv.
I need something like this for developing dry run, but am submitting this separately, so it can be picked apart separately.
> Implement a stream writer with encoding abilities.

- classes/local/execution/engine.php
- classes/local/formats/encoders/json.php
- classes/local/step/writer_stream.php
- classes/visualiser.php
- lang/en/tool_dataflows.php
- run.php
- tests/tool_dataflows_stream_writer_test.php
Resolves #90 
Add isdryrun property for engine.
Add dryrunstreamname support to writer_stream.
Add EOL to output in JSON encoder.
> Issue #90: Add support for dryruns.

- classes/dataflow.php
- classes/dataflows_table.php
- classes/local/step/base_step.php
- classes/local/step/connector_curl.php
- classes/local/step/connector_step.php
- classes/local/step/flow_step.php
- classes/local/step/trigger_step.php
- classes/local/step/writer_step.php
- classes/step.php
- classes/steps_table.php
- classes/visualiser.php
- lang/en/tool_dataflows.php
- run.php
- tests/tool_dataflows_test.php
- fix: issue if exception is thrown and engine is not defined to log it
- feat: add declaration of side effects and checks
- feat: add basic icon outputs to the different types of steps
- feat: add different styles for different step types in the visual graph
Resolves #74 
Related to #107 - still needs arrow styles
> 74 declare side effects

- classes/dataflow.php
- lib.php
- feat: add arrow styles based on their connections
Continues from #151
Example
Resolves #107
> 107 arrow styles

- classes/dataflow.php
- classes/dataflows_table.php
- classes/visualiser.php
- lang/en/tool_dataflows.php
- remove-dataflow.php
Resolves #113 
Add icon to dataflow action list.
Add button to dataflow page.
Add delete logic.
> Issue #113 Add ability to delete workflows.

- step.php
Change step.php to create step object after removing 'dependson' field.
> Issue #87: Fix saving step bug.

- classes/form/step_form.php
- classes/local/step/base_step.php
- classes/local/step/reader_sql.php
- classes/local/step/writer_stream.php
- classes/manager.php
- lang/en/tool_dataflows.php
- lib.php
- tests/tool_dataflows_sql_reader_test.php
- feat: ability to set up custom form inputs per step type
- fix: updating non-custom mstep configuration & prefixed form rel methods
Resolves #123
> 123 add step custom forms

- classes/form/step_form.php
- classes/step.php
- classes/visualiser.php
- css/step-summary.css
- lang/en/tool_dataflows.php
- step.php
- templates/step-summary.mustache
Resolves #127 
Create mustache template for the summary
Add functions to visualizer to generate messages.
> Issue #127: Display existing links and link requirements on step edit page

- classes/local/step/base_step.php
- classes/step.php
- classes/steps_table.php
- lang/en/tool_dataflows.php
- step-chooser.php
- step.php
- templates/step-chooser.mustache
- templates/step-summary.mustache
> Issue #174: Change to use display names for step types.

- classes/dataflow.php
- classes/local/step/flow_step.php
- classes/local/step/reader_step.php
- classes/local/step/trigger_step.php
- classes/step.php
- classes/visualiser.php
- lang/en/tool_dataflows.php
- step-chooser.php
- step.php
- tests/tool_dataflows_test.php
Resolve #149 
Resolves #166 
Add methods to step to validate input and output links.
> Issue #149: Add link validataions

- classes/form/step_form.php
Resolves #189 
Refactor step_form to use ordered list.
> Issue #189: Fix ordering of steps.

- classes/dataflow.php
- classes/dataflows_table.php
- classes/form/dataflow_form.php
- classes/local/execution/engine.php
- classes/visualiser.php
- dataflow-action.php
- db/install.xml
- db/upgrade.php
- lang/en/tool_dataflows.php
- run.php
- tests/local/execution/tool_dataflows_basic_execution_test.php
- tests/tool_dataflows_sql_reader_test.php
- tests/tool_dataflows_stream_writer_test.php
- tests/tool_dataflows_variables_test.php
- version.php
> Issue #126: Disable workflow flag

- classes/dataflow.php
- classes/local/execution/connector_engine_step.php
- classes/local/execution/engine.php
- classes/local/execution/engine_flow_cap.php
- classes/local/execution/engine_step.php
- classes/local/execution/flow_engine_step.php
- classes/step.php
- lang/en/tool_dataflows.php
- tests/tool_dataflows_variables_test.php
- feat: wip version of storing timing information for state changes
- fix: refactored engine labels, timing data stored & internal references
Related to #164
> 164 add state times on change

- view.php
> Issue #212: Fix breadcrumb trail display.

- classes/local/execution/engine.php
- classes/local/execution/engine_step.php
- classes/local/scheduler.php
- classes/local/step/base_step.php
- classes/local/step/connector_s3.php
- classes/local/step/connector_step.php
- classes/local/step/flow_step.php
- classes/local/step/reader_sql.php
- classes/local/step/trigger_cron.php
- classes/local/step/trigger_step.php
- classes/step.php
- classes/task/process_dataflows.php
- db/install.xml
- db/upgrade.php
- lang/en/tool_dataflows.php
- tests/local/execution/tool_dataflows_engine_test.php
- tests/tool_dataflows_scheduler_test.php
- tests/tool_dataflows_sql_reader_test.php
- version.php
Resolves #94 
Flesh out trigger_cron and process_dataflows classes.
Add timestr config to trigger_cron.
> Issue #94: Add cron trigger step

- classes/local/step/reader_sql.php
- lang/en/tool_dataflows.php
- tests/tool_dataflows_sql_reader_test.php
- feat: add support for multiline conditional SQL fragments
- docs: add help text to the SQL input, also providing a short explainer
> 194 support more optional fragments and help text

- view.php
> fix: warning caused by order and usage of $url variable

- classes/dataflow.php
- classes/local/execution/engine.php
- classes/privacy/provider.php
- classes/run.php
- db/install.xml
- db/upgrade.php
- lang/en/tool_dataflows.php
- tests/fixtures/sample-with-expressions.yml
- tests/tool_dataflows_test.php
- version.php
- feat(db): add log and runs dataflow tables
- feat: add run class and to init and entrypoints for updating state
- feat: store run data when the engine is run (not dry)
Resolves #236 
Resolves #237
> 170 setup and store runs

- classes/form/step_form.php
- classes/local/scheduler.php
- classes/local/step/trigger_cron.php
- classes/step.php
- db/install.xml
- lang/en/tool_dataflows.php
- tests/tool_dataflows_scheduler_test.php
- version.php
> Issue #219: Refactor cron trigger to use crontab format.

- classes/local/scheduler.php
- classes/task/process_dataflows.php
- tests/tool_dataflows_scheduler_test.php
> Issue #225: Remove test line that was causing a value mismatch.

- classes/dataflow.php
- classes/local/scheduler.php
- classes/local/step/trigger_cron.php
- db/install.xml
- lang/en/tool_dataflows.php
- tests/tool_dataflows_scheduler_test.php
- version.php
Resolves #242 
Refactor scheduler to record stepid for cron triggers.
Add check to dataflow validation to count trigger steps.
Refactor unit tests.
> Issue #242: Add validity check for multiple trigger steps.

- classes/form/step_form.php
- classes/import_form.php
- classes/parser.php
- fix: add name field validation as a rule to the base step form
- fix: yaml parsing validation for import form & step form
Resolves #250 
Also fixes the import page error key referenced when there was an issue.
> 250 fix uncaught errors

- classes/local/step/trigger_cron.php
> Issue #248: Fix cron trigger step validaton to work with 4.0.

- classes/local/execution/connector_engine_step.php
- classes/local/execution/engine.php
- classes/local/execution/engine_step.php
- classes/local/execution/flow_engine_step.php
Resolves #258 
This should fix both problems mentioned in the issue notes.
> Issue #258: Make connector steps execute after flow steps have finished.

- classes/local/step/reader_json.php
- lang/en/tool_dataflows.php
- lib.php
- tests/tool_dataflows_json_reader_test.php
- version.php
> Issue #207: JSON reader step

- classes/local/service/secret_service.php
- classes/local/step/base_step.php
- classes/step.php
- classes/steps_table.php
- tests/tool_dataflows_secret_service_test.php
feat: add secret service to ensure secrets are managed and contained
Table:
Export:
Logging:
Runs:
Resolves #267
> 267 handle secrets better

- classes/local/formats/encoder_base.php
- classes/local/formats/encoders/json.php
- classes/local/step/writer_stream.php
- lang/en/tool_dataflows.php
- tests/tool_dataflows_stream_writer_test.php
- version.php
> Issue #141: pretty print JSON

- classes/form/step_form.php
- classes/local/step/base_step.php
- classes/local/step/connector_s3.php
- lang/en/tool_dataflows.php
- tests/tool_dataflows_connector_s3_test.php
- version.php
- feat: convert config into form inputs and refactored usage
- feat: automatically set 'required' for relevant fields in the step type
Resolves #261
> #261 s3 copy improvements

- classes/import_form.php
- classes/local/scheduler.php
- classes/local/step/base_step.php
- classes/local/step/reader_json.php
- classes/local/step/trigger_cron.php
- classes/runs_table.php
- classes/step.php
- classes/visualiser.php
- db/access.php
- db/tasks.php
- import.php
- lib.php
- tests/local/execution/reader_sql_variable_setter.php
- tests/tool_dataflows_json_reader_test.php
- tests/tool_dataflows_scheduler_test.php
- tests/tool_dataflows_sql_reader_test.php
- view-run.php
- style: fix phpcs issues
- style: phpcs fix warnings regarding line length
Resolves  #277
> 277 phpcs fixes

- tests/local/execution/tool_dataflows_engine_test.php
> Issue #278: Add @cover comments to tool_dataflows_engine_test

- classes/local/execution/engine.php
- classes/local/step/base_step.php
- classes/local/step/connector_s3.php
- classes/step.php
- tests/tool_dataflows_connector_s3_test.php
- fixed s3 prefix removal handling
- fix directory nesting possibility for local files (e.g. path/to/file)
- add tests to cover the fixed issues
- some minor phpdoc cleanup, refactoring
Resolves #298
> fix: improved s3 handling of paths with more tests

- classes/form/step_form.php
- classes/local/scheduler.php
- classes/local/step/base_step.php
- classes/local/step/trigger_cron.php
- fix: return type of scheduler::get_scheduled_times
- docs: add missing param / typehints for phpdocs
Resolves #279
> 279 fix incorrect return type

- classes/dataflow.php
- classes/local/execution/engine.php
- db/install.xml
- db/upgrade.php
- edit.php
- version.php
> Issue #143: Store config version history

- README.md
Just a small readme update
This resolves #296
> README update : dependencies

- .github/workflows/ci.yml
- classes/visualiser.php
- tests/tool_dataflows_secret_service_test.php
- test: adjusted to exclude column(s) not in scope of what's being tested
- refactor: convert 'print exit' to exceptions which can be handled
> 314 fix dot issue unit tests

- edit.php
Just a fix to avoid this error when no config exists
Regards,
Marc
> persitent variable null condition - error fix

- classes/step.php
> Issue #322: Fix crash when deleting a step with an invalid type.

- classes/check/dataflow_runs.php
- lang/en/tool_dataflows.php
- lib.php
- version.php
> Issue #256: Add generic checks for dataflow runs

- classes/admin_setting_permitted_directories.php
- classes/helper.php
- lang/en/tool_dataflows.php
- settings.php
- tests/tool_dataflows_helper_test.php
- version.php
Resolves #297 
Expand description of permitted directories setting.
Add support for expanding [dataroot] placeholder.
> Issue #297: Clarify permitted dirs

- classes/local/step/connector_curl.php
- classes/local/step/connector_debug_file_display.php
- classes/local/step/connector_s3.php
- classes/local/step/reader_json.php
- classes/local/step/writer_stream.php
- lang/en/tool_dataflows.php
> Issue #324: Update path lang strings

- classes/local/step/connector_sns_notify.php
- lang/en/tool_dataflows.php
- lib.php
- version.php
Resolves #7 
Add connector_sns_notify step.
> Issue #7: Add SNS notification step

- classes/dataflow.php
Resolves #334 
Make importing a dataflow a transaction .
> Issue 334: Fix import

- classes/local/step/connector_wait.php
- lang/en/tool_dataflows.php
- lib.php
- tests/tool_dataflows_connector_wait_test.php
- version.php
Resolves #45.
Add connector_wait class.
> Issue #45: Wait step

- templates/run.mustache
- templates/step-chooser.mustache
- templates/step-summary.mustache
> Mustache fixes #361

- tests/tool_dataflows_secret_service_test.php
- tests/tool_dataflows_sql_reader_test.php
- tests/tool_dataflows_variables_test.php
- tests/tool_dataflows_workflow_state_test.php
- fix: unit tests for mysql, casted types in tests did not exist for mysql
- fix: issue where the s3 sdk was trying to be loaded but wasn't installed
Resolves #364 
Resolves #358
> 358 fix unit tests for mysql

- classes/local/step/flow_logic_case.php
Also added a class property passed with a description to make it clearer what the variable is used for.
Resolves #346
> fix: case logging details of the matching case

- classes/dataflow.php
- classes/step.php
> Issue #231: Escape inputs to dot cli

- classes/form/step_form.php
- classes/step.php
- lang/en/tool_dataflows.php
- tests/tool_dataflows_step_test.php
- version.php
Resolves #372
Add rule to alias element in step_form.
Add validate_alias() method to step.
Add unit tests.
> Issue #372: Fix step alias validation

- classes/dataflows_table.php
- classes/helper.php
- classes/visualiser.php
- lang/en/tool_dataflows.php
- settings.php
- step-chooser.php
- version.php
Resolves #341 
Display warnings if dot not available.
Show alternate icon to dot images.
> Issue #341: Include checks for graphviz dot dependency

- classes/local/step/writer_step.php
- classes/local/step/writer_stream.php
- tests/local/execution/array_out_type.php
- tests/tool_dataflows_stream_writer_test.php
Resolves #382 
Resolves #383 
Make having a side effect is not the default for writers.
Add has_side_effect() to writer_stream.
Set hassideeffect to true for array_out_type.
Add unit test.
> 382-side-effects:

- classes/dataflow.php
- classes/step.php
- tests/tool_dataflows_dot_escape_test.php
> Issue #231: Escape strings for dot cli

- classes/dataflow.php
- classes/form/dataflow_form.php
- classes/local/execution/engine.php
- classes/local/execution/engine_step.php
- classes/local/scheduler.php
- classes/local/step/base_step.php
- classes/local/step/reader_sql.php
- classes/local/step/trigger_cron.php
- classes/task/process_dataflow_ad_hoc.php
- classes/task/process_dataflows.php
- db/install.xml
- db/upgrade.php
- edit.php
- lang/en/tool_dataflows.php
- tests/local/execution/tool_dataflows_engine_test.php
- tests/tool_dataflows_ad_hoc_task_test.php
- tests/tool_dataflows_concurrency_test.php
- tests/tool_dataflows_connector_s3_test.php
- version.php
> Issue #169: Cron based workflows are spawned as ad hoc tasks.

- classes/step.php
> Issue #106: Rewire flow on step deletion

- classes/local/step/flow_web_service.php
- classes/local/step/writer_stream.php
- lang/en/tool_dataflows.php
- lib.php
- tests/tool_dataflows_helper_test.php
- tests/tool_dataflows_step_test.php
- tests/tool_dataflows_web_service_flow_test.php
- version.php
Hi @keevan,
I am aware there is still an issue with the state but have not been able to troubleshoot it, maybe another pair of eyes can be helpful.
Resolves #13
Regards,
Marc
> webservice step 13

- classes/local/step/connector_s3.php
- tests/tool_dataflows_connector_s3_test.php
Resolves #391 
Add validate_for_run() to connector_s3
Add unit tests
> Issue #391: validate S3 connector paths only for runs.

- classes/local/step/connector_curl.php
- tests/tool_dataflows_curl_connector_test.php
Resolves #390 
Add validate_for_run() to connector_curl.
Add unit tests.
> Issue #390: Fix curl connector to validate destination values.

- classes/dataflows_table.php
> Issue #351: Sort flows by enabled and name

- classes/local/step/connector_curl.php
- classes/local/step/connector_s3.php
- tests/tool_dataflows_connector_s3_test.php
- tests/tool_dataflows_curl_connector_test.php
Resolves #378
Add has_side_effect() to connector_curl and connector_s3
Add unit tests.
> Issue #378: has_side_effect for curl and s3

- classes/dataflows_table.php
- lang/en/tool_dataflows.php
- version.php
> Issue #352: Polish dataflows list page.

- classes/local/step/flow_logic_case.php
- lang/en/tool_dataflows.php
- tests/tool_dataflows_flow_logic_case_test.php
> Issue #376: Case step - handle no matching cases

- classes/form/step_form.php
- styles.css
- templates/available-fields.mustache
- templates/tags.mustache
Hi @brendanheywood, this is a PR for issue #311, might need to displace the group position in the grid, but the feature is here
> Resolves issue #311 feat: collapsible variables added

- .github/workflows/ci.yml
- lang/en/tool_dataflows.php
- styles.css
- templates/available-fields.mustache
- templates/tags.mustache
- version.php
> Copy variables to clipboard #310

- classes/local/step/flow_web_service.php
> fix: step to be extended from flow_step to correct output links

- classes/local/step/flow_noop.php
- lang/en/tool_dataflows.php
- lib.php
Unlike the debugging this step this does absolutely nothing with no
logs.
Resolves  #44
> Implement a noop step #44

- classes/local/execution/engine.php
- classes/local/execution/iterators/dataflow_iterator.php
- classes/local/step/writer_stream.php
- fix: clarify errors on abort by logging it earlier
- fix: handling for when no iterator value is passed through
> some flow engine logic adjustments

- classes/admin/admin_setting_yaml.php
- classes/dataflow.php
- classes/local/execution/engine.php
- lang/en/tool_dataflows.php
- settings.php
- tests/tool_dataflows_variables_test.php
Resolves #354 
Add global vars box to plugin settings.
Add global.vars to variables tree.
> Issue #354: Global variables and config settings

- classes/dataflow.php
- tests/fixtures/sample-with-expressions.yml
- tests/tool_dataflows_workflow_state_test.php
> Renamed vars #408

- lang/en/tool_dataflows.php
> Issue #403: Fix type in connector_curl:destination_help string

- classes/admin/admin_setting_yaml.php
- classes/dataflow.php
- classes/dataflows_table.php
- classes/local/provider/expression_provider.php
- classes/parser.php
- tests/tool_dataflows_variables_test.php
Added native php functions as per below:
- add count
- add isset
Also added supporting tests
Resolves #413
> feat: add more helper functions to the parser #413

- classes/local/execution/iterators/dataflow_iterator.php
This fixes the logs and internal iteration count, which records the amount of time the step has been actually processed
> fix: iterator behaviour on a false value

- classes/privacy/provider.php
> Issue #437: Fix missing lang string

- classes/local/step/flow_logic_case.php
- tests/tool_dataflows_flow_logic_case_test.php
> fix: add full variables context when evaluating case expressions

- classes/dataflow.php
- classes/form/dataflow_form.php
- lang/en/tool_dataflows.php
- version.php
> Issue #353: Add dataflow config help and allow nested variables

- classes/local/execution/logging_context.php
- run.php
> Align log statements to read easier #406

- classes/dataflow.php
- classes/helper.php
> Issue #366: Add CFG settings as variables.

- classes/local/step/flow_web_service.php
This PR solves issue #453,
Regards,
Marc
> fix: flow_web_service passes record instead of bool

- classes/dataflow.php
- classes/local/provider/expression_provider.php
- classes/local/step/connector_email.php
- lang/en/tool_dataflows.php
- lib.php
- version.php
> Email connector action

- classes/visualiser.php
- db/caches.php
- lang/en/tool_dataflows.php
Hi @brendanheywood,
This PR solves issue #458, wanted to use a 256 hash but not sure of the use in `admin/tool/dataflows/visual.php`
Regards,
Marc
> feat: Cache internal dot binaries fragments

- classes/local/step/writer_stream.php
- tests/tool_dataflows_test.php
Hi,
This PR solves issue #462
Regards,
Marc
> fix: make stream name a mandatory field

- classes/dataflows_table.php
- visual.php
> Add caching headers for graphs #387

- classes/local/step/connector_curl.php
> Issue #495: Fix dry run issue in curl connectors

- classes/local/execution/engine.php
> Issue #386: Shutdown handler to cleanup aborted requests

- classes/local/step/base_step.php
> Added output variable logging #508

- classes/local/execution/iterators/dataflow_iterator.php
- classes/local/step/flow_logic_case.php
Resolves #496
This enhancement results in exceptions being logged for the step where they occurred, giving better information.
> Issue #496: Have exceptions caught in iterator::next() implementations.

- classes/dataflow.php
- classes/local/step/reader_sql.php
- classes/parser.php
- lang/en/tool_dataflows.php
- tests/tool_dataflows_sql_reader_test.php
- version.php
> Issue #451: has_expression() is called with an array

- classes/local/execution/engine_step.php
- classes/local/execution/flow_engine_step.php
- classes/local/step/base_step.php
- classes/step.php
- tests/tool_dataflows_connector_curl_test.php
- tests/tool_dataflows_web_service_flow_test.php
- feat: add simpler methods from the step type to call
- feat: config now automatically resolves "record[*]" expressions
> various step authoring enhancements

- classes/local/execution/engine.php
- tests/tool_dataflows_web_service_flow_test.php
> Issue #511: Fix unit test in tool_dataflows_web_service_flow_test.

- db/install.xml
- db/upgrade.php
- version.php
> fix: config field type changed to text tool_dataflows_steps

- classes/local/execution/flow_engine_step.php
- classes/local/step/flow_web_service.php
- tests/tool_dataflows_web_service_flow_test.php
> refactor: change record access to be via dot notation

- classes/local/execution/engine.php
- classes/local/execution/engine_flow_cap.php
- classes/local/execution/iterators/dataflow_iterator.php
- lang/en/tool_dataflows.php
- version.php
Resolves #504 
Resolves #494 
Add new proceed_status rules to engine_flow_cap.
Remove handle_status_for_execution() as no longer needed.
> Issue #504: Fix error calling next() on null.

- classes/local/step/flow_logic_case.php
> Issue #521: Fix property on null bug

- classes/dataflow.php
- tests/tool_dataflows_variables_test.php
> Issue #517: Fix arrays converted to objects bug.

- classes/local/execution/engine.php
> Issue #512: Fix exception in shutdown function

- classes/form/dataflow_form.php
- edit.php
> Issue #472: Redirect to previous page when editing config

- classes/local/step/flow_email.php
- lang/en/tool_dataflows.php
- lib.php
- version.php
Hi,
This PR solves issue #545 
Cheers,
Marc
> feat: email connector to emailflow, and record expression support

- classes/local/step/flow_web_service.php
Hi @brendanheywood,
This PR solves servicerequireslogin issues running cron job.
Regards,
Marc
> fix: web service constant check issue bypass

- classes/form/step_form.php
> Issue #446: Fix display order bug

- classes/form/step_form.php
- templates/available-fields.mustache
Mustache might work different in Totara, but pulling this back into PHP-land and preparing the contents there seems to have helped
Resolves #556
> fix: lang string issues on step creation

- classes/visualiser.php
- templates/dataflow-actions.mustache
Check signature: 
mustache_pix_helper_testcase::test_no_exploitable_pix_helper_uses
> fix: templates containing variables in pix helpers

- classes/dataflows_table.php
- classes/runs_table.php
- classes/sql_table.php
- classes/steps_table.php
- classes/visualiser.php
- runs.php
- tests/tool_dataflows_secret_service_test.php
> fix: remove usage of close_recordset for table output

- run.php
> Increase memory and runtime limits #567

- classes/local/step/base_step.php
> Issue #532: Remove configuration field from generic step form.

- classes/local/step/flow_logic_switch.php
- db/upgrade.php
- lang/en/tool_dataflows.php
- lib.php
- tests/tool_dataflows_flow_logic_switch_test.php
- version.php
> Issue #399: Rename case to switch

- db/install.xml
- db/upgrade.php
- version.php
> fix: rename group to loggroup in logs table

- classes/dataflow.php
- classes/step.php
- tests/tool_dataflows_test.php
> Issue #481: Reduce db calls

- classes/dataflow.php
- classes/form/dataflow_form.php
- classes/form/step_form.php
- classes/helper.php
- classes/import_form.php
- classes/local/execution/connector_engine_step.php
- classes/local/execution/engine.php
- classes/local/execution/engine_step.php
- classes/local/execution/flow_engine_step.php
- classes/local/execution/iterators/dataflow_iterator.php
- classes/local/step/base_step.php
- classes/local/step/flow_logic_switch.php
- classes/parser.php
- classes/step.php
- classes/steps_table.php
- db/install.xml
- db/upgrade.php
- edit.php
- lang/en/tool_dataflows.php
- tests/fixtures/sample-export.yml
- tests/fixtures/sample-with-expressions.yml
- tests/tool_dataflows_connector_curl_test.php
- tests/tool_dataflows_sql_reader_test.php
- tests/tool_dataflows_test.php
- tests/tool_dataflows_variables_test.php
- tests/tool_dataflows_workflow_state_test.php
- version.php
Resolves #525 
Moved outputs to 'vars'.
Replaced dataflows.config with dataflows.vars.
Added config to dataflows for other settings.
> 525 output mappings

- classes/local/step/flow_copy_file.php
- lang/en/tool_dataflows.php
- lib.php
> feat: add copy file step

- classes/local/step/connector_file_exists.php
- lang/en/tool_dataflows.php
- lib.php
> feat: add file exists step

- classes/local/execution/connector_engine_step.php
- classes/local/execution/engine.php
- classes/local/execution/engine_flow_cap.php
- classes/local/execution/engine_step.php
- classes/local/execution/flow_engine_step.php
- classes/local/execution/iterators/dataflow_iterator.php
- classes/local/execution/iterators/iterator.php
- classes/local/step/flow_abort.php
- classes/local/step/reader_sql.php
- classes/local/step/writer_stream.php
- lang/en/tool_dataflows.php
- lib.php
- tests/local/execution/test_engine.php
- tests/local/execution/tool_dataflows_engine_test.php
- tests/tool_dataflows_abort_test.php
Resolves #577
Add code to check for ABORTED status
Refactor names to minimize confusion.
Add flow abort step.
> Issue #577: Fix problem with run continuing after aborted.

- classes/dataflow.php
- classes/step.php
- tests/tool_dataflows_connector_curl_test.php
- tests/tool_dataflows_connector_s3_test.php
- tests/tool_dataflows_test.php
- tests/tool_dataflows_variables_test.php
> Issue #574: Ensure dataflow's confighash has gets cleared whenever a step changes.

- classes/dataflow.php
Resolves #599 
Revert changes made to get_dotscript() as steptype->get_output_labels() doesn't work as expected.
> Issue #599: Fix dot-escape error

- classes/local/step/reader_csv.php
- lang/en/tool_dataflows.php
- lib.php
- tests/tool_dataflows_reader_csv_test.php
> feat: add reader_csv step

- lang/en/tool_dataflows.php
- fix: add missing hash file connector lang string
- style: sort the step names in the lang strings
Resolves #605
> 605 fix missing langstring

- classes/local/step/reader_sql.php
> fix(sql): execute method and docs to align with the parent class definition

- classes/local/step/trigger_cron.php
> fix: check return value of get_scheduled_times before usage

- classes/local/step/reader_csv.php
- fix: default delimiter input and set placeholder
- fix: csv reader not reading from resolved path
> 618 fix csv reader

- classes/check/dataflow_runs.php
> fix(check): action link for report

- runs.php
> fix(runs): regression by method sql_cast_char2float which doesn't exist

- classes/dataflow.php
- classes/local/execution/flow_engine_step.php
- classes/local/step/base_step.php
- classes/local/step/flow_email.php
- classes/local/step/flow_logic_switch.php
- classes/local/step/flow_web_service.php
- classes/local/step/reader_sql.php
- classes/parser.php
- classes/step.php
- tests/tool_dataflows_variables_test.php
> Issue #647: Refactor parser class to be a singleton.

- classes/local/step/connector_sftp.php
- refactor(sftp): move core use-cases into separate methods
- refactor(sftp): key resolution and public host checks into own methods
Related to PR #621 - https://github.com/catalyst/moodle-tool_dataflows/pull/621#pullrequestreview-1138273650
> 37 sftp connector tweaks

- classes/dataflow.php
- classes/local/step/flow_noop.php
- classes/local/step/flow_set_variable.php
- classes/local/step/set_variable_trait.php
- lang/en/tool_dataflows.php
- lib.php
- tests/tool_dataflows_flow_set_variable_test.php
> feat: add step to allow setting any value in the vars tree

- classes/local/variables/var_value.php
- tests/tool_dataflows_variables_new_test.php
> Issue 683: Fix clear_dependent() to correctly remove dependents.

- classes/local/step/connector_curl.php
- classes/local/step/trigger_event.php
- tests/tool_dataflows_connector_curl_test.php
Hi, this is a PR fixing empty raw post data sending. (cf: issue #687)
Regards,
Marc
> Issue #687: empty post raw data sent fix

- thirdpartylibs.xml
> Issue #693: Fix thirdpartylibs.xml to prevent vendor from being checked by CI.

- classes/helper.php
- tests/tool_dataflows_helper_test.php
- version.php
> Issue 142: Fix helper::path_is_relative() and helper::path_validate() to expand [dataroot] placeholder before testing.

- classes/local/step/connector_noop.php
- lang/en/tool_dataflows.php
- lib.php
Deliberately not doing a version bump because of the other PRs that are currently open.
> Add connector noop.

- classes/local/step/append_file_trait.php
- lang/en/tool_dataflows.php
- tests/tool_dataflows_append_file_step_test.php
- version.php
Will strip the first line when appending, but not if the file is empty.
> Issue 707: Strip file list when appending files.

- classes/dataflow.php
- classes/form/dataflow_form.php
- db/install.xml
- db/upgrade.php
- tests/tool_dataflows_test.php
- version.php
> Issue #704: Add description to dataflows.

- classes/local/formats/encoders/csv.php
- lang/en/tool_dataflows.php
- tests/tool_dataflows_reader_csv_test.php
- version.php
Also add headers to beginning of file.
> Fix CSV encode to put an EOL at end of file.

- classes/local/execution/engine.php
> More helpful debugging

- classes/form/dataflow_form.php
- lang/en/tool_dataflows.php
- version.php
> Issue #696: Add validation to dataflow config form.

- classes/local/step/gpg_trait.php
- classes/local/step/set_variable_trait.php
Resolves #729 
Includes a trivial fix in GPG step.
> Issue #729: Fix set variable step to not persist during dry runs.

- classes/local/step/reader_csv.php
- tests/tool_dataflows_reader_csv_test.php
> Issue 722: Throw exception when cannot open input.

- classes/local/step/append_file_trait.php
- classes/local/step/gpg_trait.php
- classes/local/step/remove_file_trait.php
- classes/local/step/s3_trait.php
- classes/local/step/sftp_trait.php
- tests/tool_dataflows_append_file_step_test.php
- tests/tool_dataflows_connector_s3_test.php
- tests/tool_dataflows_gpg_test.php
- tests/tool_dataflows_sftp_test.php
> Issue #756: Refactor has_side_effect() to evaluate expressions.

- classes/local/step/connector_append_file.php
- lang/en/tool_dataflows.php
- lib.php
> feat(append): add append connector step

- classes/local/step/gpg_trait.php
> fix(gpg): add --no-tty and --batch option to fix encryption

- classes/admin/admin_setting_configcheckbox.php
- classes/admin/admin_setting_configexecutable.php
- classes/admin/admin_setting_configtext.php
- classes/admin/admin_setting_permitted_directories.php
- classes/admin/readonly_trait.php
- classes/form/dataflow_form.php
- classes/form/import_form.php
- classes/form/step_form.php
- classes/local/step/flow_sql.php
- classes/manager.php
- dataflow-action.php
- import.php
- index.php
- lang/en/tool_dataflows.php
- settings.php
- step-chooser.php
- tests/tool_dataflows_flow_sql_test.php
- view.php
- style: phpcs fixes
- feat: add readonly flag to lock dataflow settings
- feat: add readonly checks to all the forms
> 786 add readonly flag to lock dataflow settings

- classes/local/step/flow_email.php
- lang/en/tool_dataflows.php
- version.php
Hi, 
This is a small improvement to the flow email step that permits the use of a text editor - and a more customisable email.
Regards,
Marc
> Issue #792: Improvement flow_email text to editor

- classes/local/step/flow_sql.php
> [#797] fix: sql flow step to switch cases in case insensitive manner

- classes/local/provider/expression_provider.php
- classes/local/step/flow_web_service.php
- version.php
> Issue #781: Add config to set webservice step params as lowercase

- classes/local/provider/expression_provider.php
- classes/local/step/sql_trait.php
- lang/en/tool_dataflows.php
- version.php
Hi @keevan,
I have found an alternate way to do what tickets 399328 demands, however this needs small changes included in this PR,
Regards,
Marc
> Moodle 35 stable 690

- classes/local/step/flow_transformer_regex.php
- lang/en/tool_dataflows.php
- version.php
> feat: named capture group support for regex transformer step

- classes/local/execution/iterators/dataflow_iterator.php
- classes/local/provider/expression_provider.php
- classes/local/step/directory_file_list_trait.php
- classes/local/step/flow_transformer_filter.php
- classes/local/variables/var_value.php
- lang/en/tool_dataflows.php
- version.php
- feat: add natural sort to directory file list trait
- fix: logs from steps now hold the correct context
- feat: get dynamic vars with expression get_var()
Resolves #819 
Resolves #818
> Dynamic vars, logging fix and natural sort

- classes/local/step/copy_file_trait.php
> Update file glob copy to work on single files

- run.php
Turns out 5 mins isnt that long when the real world hits
> Raise execution timeout

- classes/local/execution/engine.php
> fix: add more logging to shutdown and signal handler

- classes/dataflows_table.php
> fix: dataflow table view

- run.php
> fix: ignore user abort / client disconnects for a manual run

- styles.css
**Description:** Nests CSS classes that could clash with other styles in Moodle under the ` .path-admin-tool-dataflows` class. This class is appended to the body tag by Moodle. This resolves Issue #896.
> Issue #896 Ensure CSS classes do not clash with other Moodle CSS classes

- classes/local/step/reader_sql.php
- classes/local/step/sql_trait.php
Cherry pick of https://github.com/catalyst/moodle-tool_dataflows/pull/912 to latest branch
> [#911] fix sql cleaning

- classes/local/provider/expression_provider.php
> issue #915: allow floor php function

- classes/local/provider/expression_provider.php
> Issue #919 allow str and array functions

- classes/local/provider/expression_provider.php
> Issue #919: Allow str and array functions

- classes/local/step/adl_trait.php
- classes/local/step/connector_adl.php
- lang/en/tool_dataflows.php
- lib.php
- tests/tool_dataflows_connector_adl_test.php
This resolves the feature request: https://github.com/catalyst/moodle-tool_dataflows/issues/891
> Add Azure datalake blob file copy support

- classes/local/step/reader_array.php
- lang/en/tool_dataflows.php
- lib.php
- recipes/README.md
- recipes/array_reader_demo.yml
- tests/tool_dataflows_reader_array_test.php
- version.php
> Issue #959: add array reader step.

- classes/local/step/trigger_event.php
- classes/step.php
- tests/tool_dataflows_event_processor_test.php
- version.php
Also
- Fix deprecation notices in unit test.
- Fix get_steptype() bug in step.
- Fix deprecation notices in step.
> Issue #954: Fix get_events_list() to work with 4.3 changes.

- classes/local/execution/iterators/dataflow_iterator.php
- classes/local/step/flow_cap.php
- classes/local/step/reader_array.php
- classes/step.php
- lang/en/tool_dataflows.php
- lib.php
- recipes/README.md
- recipes/array_reader_demo.yml
- tests/tool_dataflows_reader_array_test.php
- version.php
> Issue #959: Backport array reader step to 401.

- classes/local/provider/expression_provider.php
Resolves #968 
Specifically json_encode and htmlspecialchars.
> Issue #968: Add encode functions to the expression language

- classes/local/step/reader_csv.php
See also: https://github.com/catalyst/moodle-tool_dataflows/issues/889
> Remove reader_csv maximum line length limitation
