catalyst/moodle-tool_dataflows

classes/manager.php, classes/step/debugging.php, classes/step/step.php, tests/tool_dataflows_test.php
This only populates the list of available steps supplied by other plugins.
Currently I have added an example one which only ingests some data and outputs the same data, whilst doing a side effect of passing it to debugging in json format.
Related to #20
=> Add callback classes handling

.github/workflows/ci.yml, lib.php, tests/tool_dataflows_test.php
- test: add test for example local_aws and available custom steps
This would ideally be merged after PR #66 
Added https://github.com/catalyst/moodle-local_aws/tree/ci-for-tool_dataflows with an example step type to test out this functionality. This would also be a good candidate to add to the README.
Resolves #20
=> add optional test for custom step - tested via CI, using a custom local_aws branch

classes/execution/connector_engine_step.php, classes/execution/engine.php, classes/execution/engine_flow_cap.php, classes/execution/engine_step.php, classes/execution/flow_engine_step.php, classes/execution/iterators/iterator.php, classes/execution/iterators/map_iterator.php, classes/execution/iterators/php_iterator.php, classes/step/base_step.php, classes/step/connector_step.php, classes/step/debugging.php, classes/step/flow_cap.php, classes/step/flow_step.php, classes/step/join.php, classes/step/mtrace.php, classes/step/void_step.php, tests/execution/array_in_type.php, tests/execution/array_out_type.php, tests/execution/tool_dataflows_basic_execution_test.php, tests/execution/tool_dataflows_engine_test.php
Resolves #29 
Adds an execution engine.
Requires https://github.com/catalyst/moodle-local_aws/pull/43
The refactoring of step type classes is needed to avoid a ton of repetition.
OK to squash
=> Basic execution 2

edit.php, step.php
- fix: cancel step form now redirects to the dataflow steps list page
- fix: cancel dataflow form now redirects to the dataflows overview page
Resolves #71
=> Cancel form to do proper redirect

classes/steps_table.php, step.php
Note that dataflow is only required when adding a new step, and is otherwise loaded from the step record if that is provided instead.
Updated the table links to reflect the new changes
Resolves #81
=> fix: step add/edit page query param handling

classes/step/flow_step.php, lang/en/tool_dataflows.php, tests/execution/array_in_type.php, tests/execution/tool_dataflows_basic_execution_test.php, tests/tool_dataflows_test.php
Resolves #102 
Make 1 inputstream the default min requirement for flow steps.
Add check that mapping steps have at least 1 input.
Add inputstream restriction to array_in_type.
Change use of debugging steptypes to array_in in unit tests.
OK to squash.
=> Issue #102: Fix dataflow run error

classes/visualiser.php
Resolves #131 
Change button colour to be danger for invalid, success for valid.
Change icon to show stop icon when invalid.
=> Issue #131: Change run now button to match validation

classes/local/execution/engine.php, classes/local/execution/engine_step.php, classes/local/execution/flow_engine_step.php, classes/local/execution/iterators/php_iterator.php, classes/local/step/base_step.php, classes/local/step/flow_transformer_filter.php, classes/local/step/reader_sql.php, classes/parser.php, classes/step.php, lang/en/tool_dataflows.php, tests/local/execution/tool_dataflows_basic_execution_test.php, tests/tool_dataflows_sql_reader_test.php
- feat: add optional query fragments and variable setting for reader_sql
- feat: add expressions support to the dataflow engine and sql reader
- fix: reduce noisy expression parsing by splitting methods
- test: fix/add tests and skip empty evaluated sql expressions
Related to #5
=> 5 variable setting from engine run

classes/dataflow.php, classes/local/execution/engine.php, classes/local/execution/engine_step.php, tests/local/execution/array_in_type.php, tests/local/execution/reader_sql_variable_setter.php, tests/tool_dataflows_variables_test.php
- add supporting tests
- reader_sql_variable_setter class contains an example of how it can be set, and the tool_dataflows_variables_test test class shows how it can be retrieved (directly) and via an expression.
Resolves #5
=> feat: add global and dataflow level variable setting

step.php
Noting that for new steps, it will use the "New step" placeholder text as the step's label as shown below:
Resolves #173
=> fix: issue loading to add a new step from the step chooser

classes/local/step/reader_sql.php
Resolves #178
Tested against, and it will also Resolves #177
=> fix: reader_sql where the counterfield was referced even if it was empty

classes/local/step/reader_sql.php, classes/step.php
- fix: export, expressions from being recursively looked up & validation
- fix: sql reader not parsing some expressions before executing query
Fixes points 1 and 4 in #194
Example of a dataflow which shouldn't run, which would currently lock up, until this patch is applied:
[sql_20220610_0125.yml.txt](https://github.com/catalyst/moodle-tool_dataflows/files/8875051/sql_20220610_0125.yml.txt)
=> fix some config and expression parsing

classes/local/execution/engine.php, classes/local/step/writer_stream.php, lang/en/tool_dataflows.php
Resolves #190 
Add exception message to engine abort log.
Add log calls to writer_stream when errors occur.
Add extra checks to writer_stream when errors occur.
=> Issue #190: Enhance abort logging

classes/local/execution/engine.php, classes/local/execution/engine_step.php, classes/local/execution/logging_context.php
Resolves #188 
Add class logging_context
Encapsulate logic for creating a log inside the context object.
Added a context object for use in logging. This encapsulates the logging logic, separating it from other classes. This obejct can be easily expanded when needed.
=> Issue #188: Create logging contexts

classes/dataflow.php, classes/exportable.php, classes/local/step/base_step.php, classes/step.php
Example of result after:
Can probably refactor to pass through a helper function which applies the defaults indentation, spacing levels and multiline flags. But this was the quickest in place option for now.
Resolves #208
=> fix: yaml parsing for saving/imports to allow for multiline literal view

classes/local/execution/engine.php, classes/local/step/base_step.php, classes/local/step/connector_curl.php, classes/local/step/connector_debugging.php, classes/local/step/connector_s3.php, classes/local/step/connector_step.php, classes/local/step/flow_cap.php, classes/local/step/flow_step.php, classes/local/step/reader_sql.php, classes/local/step/reader_step.php, classes/local/step/trigger_cron.php, classes/local/step/trigger_step.php, classes/local/step/writer_step.php, classes/local/step/writer_stream.php, classes/step.php, lang/en/tool_dataflows.php, tests/local/execution/array_in_type.php, tests/local/execution/array_out_type.php, version.php
Resolves #204 
Also included cleanup for the $stepdef member.
Refactor to have stepdef and enginestep members set in the constructor of base_step.
Remove stepdef and enginestep from parameter list of all functions in step type classes.
Refactor step::get_steptype() to pass itself to the constuctor of the steptype class.
Refactor engine to pass the stepdef and itself to the constructor of the steptype, in order to generate the engine.
Change get_engine_step() to just return the engien step.
Add generate_engine_step() to generate to engine step.
Refactor all step type classes to call generate_engien_step instead of get_engine_step.
=> Issue #204: Cleanup step type classes.

classes/local/execution/engine.php, tests/tool_dataflows_workflow_state_test.php
- feat: the engine is now exportable
- test: add test to check data dumped contain expected field and changes
This is a precursor to storing all the state required in the DB, to later resume paused dataflows runs
Related to tasks 1-3 of #187
=> 187 dump the state

classes/import_form.php
This is to avoid the need to rename the file when uploaded to and from places like GitHub
Resolves #232
You can use this file to test if the new changes work:
[example-dataflow.yml.txt](https://github.com/catalyst/moodle-tool_dataflows/files/8972827/example-dataflow.yml.txt)
=> feat: add .txt as a valid file to import, with contents expected in yaml

classes/form/step_form.php
=> fix: error message contained the wrong alias used

classes/local/step/reader_sql.php, lang/en/tool_dataflows.php
This is when the variable used in the expression, could not be resolved. This is likely because the variables array provided during evaluation did not exist as a property/key.
Full output looks like the following (given this workflow: [Delta_export_of_users_20220701_0542.yml.txt](https://github.com/catalyst/moodle-tool_dataflows/files/9025686/Delta_export_of_users_20220701_0542.yml.txt)):
```
2022 Jul  1, 15:41:59.650 Engine "Delta export of users": status: new 
2022 Jul  1, 15:41:59.660 Engine "Delta export of users", step "SQL reader": status: new 
2022 Jul  1, 15:41:59.660 Engine "Delta export of users", step "write to csv": status: new 
2022 Jul  1, 15:41:59.661 Engine "Delta export of users", step "SQL reader": status: initialised 
2022 Jul  1, 15:41:59.661 Engine "Delta export of …
```
=> fix: clarify output for one class of expression parsing errors

classes/helper.php, classes/local/execution/engine.php, classes/local/step/writer_stream.php, lang/en/tool_dataflows.php, settings.php, version.php
=> Issue #158: Add a scratch directory for dataflows.

classes/dataflow.php, classes/local/execution/engine.php, classes/run.php, classes/runs_table.php, classes/visualiser.php, db/install.xml, db/upgrade.php, lang/en/tool_dataflows.php, runs.php, styles.css, templates/run.mustache, tests/tool_dataflows_scheduler_test.php, version.php, view-run.php
Added UI for dataflow runs, fixing some issues with data stored and added some (more) color to the new pages.
Testing colors for now, each run represents a different state. Can be tweaked later.
Dataflow details page:
Color Palette:
Runs view page:
All runs page:
NTS: 
Resolves #170
=> 170 ui for runs

classes/form/step_form.php, lang/en/tool_dataflows.php, templates/available-fields.mustache, version.php
Here's a preview:
Note that it doesn't have run-time variables available, in particular, it doesn't list flow variables within the same scope as the flow, but that's okay, it's still reference-able currently.
TIP: that you should also see the value (if set) of the corresponding key when hovering over the particular entry (e.g. with the mouse over the curl url)
Resolves #199
=> feat: show a list of available, known fields usable in expressions

classes/dataflow.php, classes/local/step/connector_s3.php, classes/step.php, edit.php, tests/tool_dataflows_secret_service_test.php
There's a bug in phpcs that is preventing these checks from catching all cases. With this in mind, I've opted to use the Drupal standards to catch these missing cases which seems to work well. The rule is "Drupal.Arrays.Array.CommaLastItem"
Adds on to the PR which resolved #277
I've installed the standards as follows for those wondering:
```
composer global require drupal/coder
cd /usr/share/php/PHP/CodeSniffer/src/Standards/
sudo ln -sf /home/currentuser/.config/composer/vendor/drupal/coder/coder_sniffer/Drupal Drupal
sudo ln -sf /home/currentuser/.config/composer/vendor/slevomat/coding-standard/SlevomatCodingStandard SlevomatCodingStandard
```
=> style: fix remaining trailing comma phpcs issues

classes/local/step/connector_curl.php, lang/en/tool_dataflows.php, tests/tool_dataflows_curl_connector_test.php
Hi @brendanheywood,
This is PR for issue #167,
Regards,
Marc
=> Issue #167: curl step

classes/dataflow.php, classes/dataflows_table.php, classes/form/step_form.php, classes/step.php, classes/steps_table.php, step.php
Resolves #273 
Manage flows page loads, and going into the dataflow and step no longer stops with an exception. The user can still navigate around as intended.
=> fix: step through fixing issues shown in the UI for an invalid step type

.github/workflows/ci.yml
Initially added a way to skip dot graph generation if the path is not set, but there wasn't a quick way to include the necessary config values, which would have resulted in a fixed added option in reusable workflows which isn't great. 
For now, adding the dot CLI will cause the unit tests to fail successfully
Resolves #290
=> fix: restrict generation of the dot graph to when site has set pathtodot

.github/workflows/ci.yml
This is to ensure a consistently clean codebase.
Resolves #292
=> chore: CI will now fail on codechecker warnings/errors

classes/step.php, tests/tool_dataflows_curl_connector_test.php, tests/tool_dataflows_secret_service_test.php
resolves #289 
Removed '\n' from expected value in curl_connector_test.
Swapped to values so the expected value is passed first.
Changed step::get_config() to get steptype from get_steptype. This fixed
weird error where isset($this->type) was returning false even though it has a value.
=> Issue #289: Fix failing unit tests.

classes/local/step/reader_json.php, lang/en/tool_dataflows.php, tests/tool_dataflows_json_reader_test.php, version.php
- fix: example key usersdetails corrected to userdetails
- feat: add sort order to the json reader step
Resolves #264
=> 264 add sort order to json reader

classes/dataflow.php, classes/local/execution/connector_engine_step.php, classes/local/execution/iterators/dataflow_iterator.php, classes/local/step/base_step.php, classes/local/step/connector_curl.php, classes/parser.php, classes/step.php, tests/tool_dataflows_curl_connector_test.php, tests/tool_dataflows_variables_test.php
Resolves #260 
tl;dr:
- steps expose their variables
- you declare what you want from the step
- you can use that in steps that come after
What this doesn't do is modify the input as it flows through. The concern was with a step doing too many things, and if used in another step later on such as a json writer step, you don't necessarily want the input (json / php object flowing through) to be polluted with all these additional things you've picked up along the way.
I think there should be a some _transformer_ step which uses these output variables and will explicitly update the input as it flows through, when required.
=> 260 add more flexible vars

classes/local/execution/engine.php
This was sometimes masking the underlying error message from being shown, showing instead some internal state validation message.
After patch, the abort reason is clearly shown:
```
2022 Jul 25, 18:23:47.434 Engine "I'm on the case!": Aborted: Table "tool_dataflows_versions" does not exist 
2022 Jul 25, 18:23:47.435 Engine "I'm on the case!": moodle_exception: Attempting to change the status of a dataflow engine after it has concluded. in /var/www/moodle/admin/tool/dataflows/classes/local/execution/engine.php:485
Stack trace:
#0 /var/www/moodle/admin/tool/dataflows/classes/local/execution/engine.php(362): tool_dataflows\local\execution\engine->set_status(8)
#1 /var/www/moodle/admin/tool/dataflows/classes/local/execution/engine.php(341): …
```
=> fix: change order in which engine->abort logs the reason for aboting

classes/runs_table.php, lang/en/tool_dataflows.php, version.php, view-run.php
Lang string key and value copied as-is from newer moodle's lang/en/langconfig.php
Resolves #355
=> fix: add lang strings that were missing in moodle 311 and below

classes/local/step/base_step.php, classes/local/step/writer_stream.php, classes/step.php
Resolves #335 
Add validate_for_run() to base_step to perform extra validation for runs.
Move path check in writer_stream into validate_for_run().
=> Issue #335: Fix importation of dataflows with bad path names.

classes/admin/admin_setting_permitted_directories.php, classes/helper.php, lang/en/tool_dataflows.php, settings.php, tests/tool_dataflows_helper_test.php, tests/tool_dataflows_json_reader_test.php, tests/tool_dataflows_permitted_dir_test.php, tests/tool_dataflows_stream_writer_test.php, version.php
Resolves #374 
Add checks to get_permitted_dirs() to exclude empty values.
Fix unit tests.
Add more unit tests
Remove empty lines before saving value.
Moved admin_setting_permitted_directories to classes/admin.
=> Issue #374: Fix Permitted directories bug

classes/local/step/flow_logic_case.php, lang/en/tool_dataflows.php, tests/tool_dataflows_flow_logic_case_test.php
Previously it would push the record downstream if an out of order step's expression was truthy.
Also adjusted the help text to make this a bit clearer in how it is expected to work
Resolves #347
Example workflow:
[one_direction_20220729_0119.yml.txt](https://github.com/catalyst/moodle-tool_dataflows/files/9215239/one_direction_20220729_0119.yml.txt)
This should flow in one downstream, and store all results in one file. The other file should be empty, even though both expressions are truthy
Lang string changes:
No placeholder shown:
=> fix: case matching order to evaluate cases in order

classes/form/step_form.php
Co-Authored-By: null <marcghaly@users.noreply.github.com>
Resolves #411 
Issue was caused by the position calling get_output_label, but the position value was null. This shouldn't be possible normally and is fixed in another PR #419, but this should cover both cases gracefully regardless.
=> fix: value passed to get_output_label should not be null

classes/form/step_form.php
Previously it would not show any 'positions' that have already been taken. Now it will show them all (filtered down to options set if labels are set)
Resolves #427
=> fix: show all output options for any selector when editing a step

classes/parser.php
I've added both a an apcu cache or a file cache if apcu isn't installed but the result are so far anti climactic and the expressions are still a major bottleneck. I can also see the cache being populated so it is clearly working.
There a few steps which are not using parser.php but that can't fully account for it
#470 470
=> Added expression caches #470

classes/form/step_form.php
This will be equal to just the class name, and later on, the class names will be simplified to something like 'curl' or 'sql' which will be even better, so opted to not do anything too opinionated here.
Resolves #488
=> feat: when creating a new step the name will be prefilled automatically

classes/local/execution/engine.php, classes/run.php
Resolves #510 
The fix used is not available in PHP 7.1. So in 7.1, the sample given will result in a 'Malformed UTF-8 characters, possibly incorrectly encoded' exception.
=> Issue 510: Fix get_export_data()

classes/local/step/connector_curl.php, patch/TOTARA_16_STABLE.diff, tests/application_trait.php, tests/tool_dataflows_connector_curl_test.php, tests/tool_dataflows_variables_test.php, tests/tool_dataflows_web_service_flow_test.php
- feat: allow curl step to use alternative curl class
- fix: web request unit tests for t16+
Resolves #549
=> fix t16 unit tests

step.php
In this case, they would mean the same thing, but for now the caller will ensure the data is passed to the method in the right format
Resolves #561
=> fix: default dependson to an empty array if null

classes/step.php
This was previously setting it even if the value was zero (in string form)
Resolves #555
=> fix: step links only when there is a step record

db/upgrade.php, version.php
Resolves #579
It should not cause any problems if the database has already been updated.
The diff shows the logroup block being shifted, when it was the output remapping group that was shifted.
=> Issue #579: Change version of output remappings.

classes/helper.php
This is only if the step type class properly uses the recommended `...engine->resolve_path` method
Resolves #585
=> fix: [dataroot] used in step config now autoresolves

classes/local/execution/iterators/dataflow_iterator.php, classes/runs_table.php, classes/step.php, step.php, styles.css, tests/tool_dataflows_workflow_state_test.php, view-run.php
- style: tweak to allow any debugging to come through visible and clear
for example: anything outputted in pre tags will stay the same font size
- fix: depends on must be an array, not null
- fix(runs): table display, set param type to float, expect float/int but received string
- fix: state timestamps can be referenced at any time
This means usage across steps won't be dependent on that state having existed prior to checking. The default value is null.
=> misc bugfix and improvements

classes/helper.php, classes/local/step/connector_curl.php, classes/local/step/reader_sql.php, db/upgrade.php, lang/en/tool_dataflows.php, tests/tool_dataflows_connector_curl_test.php, tests/tool_dataflows_helper_test.php, tests/tool_dataflows_variables_test.php, version.php
Resolves #392 
Refactor code to handle headers as plain text
Handle multiple headers in bash command.
Add bash escaping.
Other fixes.
=> Issue #392: Improve handling of curl headers in connector_curl

import.php
Now only redirects on successful import.
Errors will now display with slightly more detail as shown below, instead of just the top line.
Resolves #610
=> fix: display import related issues with slightly more detail

tests/tool_dataflows_variables_test.php
Cast the values to a bool to check if they equate to the expected values
=> fix: tests where values which are stored as ints are checked as bools

runs.php
Seemed to be sorted alphabetically instead of numerically. Also had to adjust the query to allow for proper types to be returned for the name field.
It's now fixed and works as expected.
Resolves #576
=> fix: order of all runs

classes/dataflow.php, classes/local/execution/engine.php, classes/local/step/trigger_cron.php, classes/local/variables/var_node.php, classes/local/variables/var_object.php, classes/local/variables/var_root.php, classes/local/variables/var_value.php, tests/local/execution/var_object_for_testing.php, tests/test_dataflows.php, tests/tool_dataflows_abort_test.php, tests/tool_dataflows_variables_new_test.php
Issues fixed:
1 - An import use statement should never start with a leading backslash
1 - Blank line found at start of control structure
3 - Each line in an array declaration must end in a comma
2 - Expected a blank line after function
5 - Expected a blank line before function
1 - Expected a space after FUNCTION keyword
1 - Multi-line array contains a single value
=> style: phpcs fixes

classes/local/step/connector_curl.php, classes/local/step/trigger_cron.php
This PR solves an undefined error aborting cron run and an unfound curl class.
Regards,
Marc
=> Moodle 35 stable cronandcurl

classes/local/step/flow_sql.php, classes/local/step/reader_sql.php, classes/local/step/sql_trait.php, classes/local/step/writer_stream.php, lang/en/tool_dataflows.php, lib.php, tests/tool_dataflows_flow_sql_test.php, version.php
1. New `flow_sql` step - this is for reading a single row using for e.g. variables. 
3. Refactored `reader_sql` with a new `sql_trait` - this is shared by the new `flow_sql` step. Note not all of the functions have been moved into the trait, for e.g. the row counting variable logic is redundant in the flow_sql step, so it only exists within the reader_sql step.
4. Fixed a tiny bug with the `stream_writer` that was causing the flow_sql unit tests to fail #673
Create a small test course to generate users, then import the test dataflow  (rename to yml github doesn't allow straight yaml)
[Test_20221121_0211.txt](https://github.com/catalyst/moodle-tool_dataflows/files/10052034/Test_20221121_0211.txt)
This dataflow does the following:
1. Uses the sql reader to read enrolments and gets the …
=> Add sql flow step

classes/local/variables/var_value.php
This issue happens with latest flow provided in ticket 384019, adding a variable in web service flow ${{ steps.get_course_details.vars.<var> }}
=> Nested Loop fix : strict value comparison add_dependent method

classes/local/provider/expression_provider.php, lang/en/tool_dataflows.php
Hi this PR includes 2 commits, one for the dataflow description in `set_variable` and another one adding `strtotime` function to expression provider, which is necessary to convert ISO 8601 date format to unix timestamp.
Regards,
Marc
=> Moodle 35 stable langfix

NEW_STEP.md, classes/local/execution/iterators/dataflow_iterator.php, classes/local/execution/iterators/iterator.php, classes/local/step/file_put_content_trait.php, classes/local/step/flow_logic_switch.php, classes/local/step/flow_sql.php, classes/local/step/flow_step.php, classes/local/step/flow_transformer_filter.php, classes/local/step/trigger_event.php, tests/tool_dataflows_abort_test.php, tests/tool_dataflows_flow_transformer_filter_test.php, version.php
Resolves #715 #716
Remove boilerplate at beginning of dataflow_iterator::next(). Change iterator::next() signature to not return anything. Change dataflow_iterator::next() to set the current value to the return value of step::execute(). Fix steps to always return a value.
Fix flow_transformer_filter step
Add flow_transformer_filter unit test
Fix unit tests.
=> Issue #716: Fix so that values can be passed through.

classes/local/step/flow_sql.php, classes/local/step/reader_sql.php, classes/local/step/sql_trait.php, tests/tool_dataflows_sql_reader_test.php
SQL could be broken with values from a variable like `'`. Each variable is now processed as a parameter, and the whole SQL processed as a prepared statement
=> Refactor SQL execution to use prepared statements

classes/local/step/gpg_trait.php, version.php
This allows errors with the gpg command to show up in the output of a manual run, as well as log to the error log.
=> fix (gpg): show output on failure

classes/step.php, tests/fixtures/sample-cron.yml, tests/tool_dataflows_test.php
Closes #778 
-  <strike>Since we cannot override the persistant's `save` function, I made a new function `save_step` which calls both `save()` and any `on_save()` callbacks</strike>
-  <strike>Hopefully this means in the future we don't run into this issue for anything else that uses this callback, as long as we are using `save_step`</strike>
- Have just added hook callbacks for after updating and after creating to trigger the steptype and dataflow save callbacks.
- Added unit tests for the cron trigger to unit test this as well
**Manual testing:**
- Upload the attached yml file [Test_flow_2_21313123_20230606_0157.txt](https://github.com/catalyst/moodle-tool_dataflows/files/11659409/Test_flow_2_21313123_20230606_0157.txt)
- Check that a record was made in `mdl_tool_dataflows_schedule`
=> [#778] bugfix: register schedule when importing cron steps

classes/local/event_processor.php, classes/task/process_dataflow_ad_hoc.php, classes/task/process_dataflows.php, tests/tool_dataflows_ad_hoc_task_test.php, tests/tool_dataflows_flow_transformer_alter_test.php, tests/tool_dataflows_json_reader_test.php, tests/tool_dataflows_test.php, tests/tool_dataflows_workflow_state_test.php, version.php
Closes #768 
- Now when scheduled task is run, it simply makes an adhoc task for each dataflow. It does not try to run one in the same thread - this is much cleaner and simpler.
- The adhoc tasks now only take in a dataflow id - no other custom data is allowed. This ensures they can be de-duplicated
- Will de-duplicate adhoc tasks based on concurrency settings
-  Covered by unit tests.
=> 768 fix concurrency

view-run.php
=> fix: cast run's timestamp to int for display

classes/local/step/directory_file_list_trait.php, lang/en/tool_dataflows.php, version.php
- feat(directory-file-list): add different return value formats: absolutepath, basename, relativepath
- feat(file-directory-list): add glob braces for multi pattern support
Relative path output with glob brace support, pattern of `{*,**/*}`
Relative path output with pattern `**/*`
Absoulte path output, pattern `**/*`
Basename (which is the default), pattern `**/*`
=> #783 improve directory file list step

classes/dataflow.php, classes/external/trigger_dataflow.php, classes/local/step/trigger_webservice.php, db/services.php, lang/en/tool_dataflows.php, lib.php
Currently adds the dataflow to the adhoc task queue, and does not process it in place. This is typically the recommended default for api calls.
Closes #790
=> feat: add webservice trigger

classes/local/step/flow_logic_switch.php, classes/local/step/flow_sql.php, tests/tool_dataflows_flow_sql_test.php, tests/tool_dataflows_reader_csv_test.php
This is set to work with the limitations of the variable node tree, where a node cannot change its type from a value node to an object node. Setting it always as an object allows it to sometimes contain the record returned, and sometimes being an empty object (when no results are found)
Resolves #799
=> [#799] fix: flow sql step sets data as objects always

classes/local/step/reader_csv.php
This fixes the warning when no delimeter is set, and it's unlikely that the delimeter is intentionally an empty value.
Closes #794
=> fix: set default delimeter when delimeter value is not truthy

tests/tool_dataflows_connector_curl_test.php
Removed OK check,
HTTP status check still exists, and though all is working for 39+, 38 and below are failling on the OK check for POST requests specifically.
Removing as it's not a very reliable test and has caused a lot more grief than it's worth.
It shouldn't ever not return OK unless the post data was somehow mangled:
https://github.com/moodlehq/moodle-exttests/blob/master/test_post.php
But somehow it is, and perhaps the CURL works differently in those versions. 
Happy to consider a more reliable endpoint/method down the track or if it becomes an issue on a real environment.
=> fix: broken curl test

classes/form/step_form.php, classes/local/step/base_step.php, classes/local/step/flow_sql.php, classes/local/step/reader_sql.php
=> [#809] fix: SQL input field width to improve UX for larger queries

classes/local/step/reader_csv.php, lang/en/tool_dataflows.php, tests/tool_dataflows_reader_csv_test.php, version.php
Resolves #807
This is what it looks like.
Added a test to ensure it works as expected.
=> feat: config to overwrite headers for csv reader

classes/local/step/connector_sftp_directory_file_list.php, classes/local/step/directory_file_list_trait.php, classes/local/step/reader_sftp_directory_file_list.php, classes/local/step/sftp_directory_file_list_trait.php, classes/local/step/sftp_trait.php, lang/en/tool_dataflows.php, lib.php, tests/tool_dataflows_sftp_test.php
- feat: sftp directory list connector step
- feat: reader step for SFTP directory listing
Preview of what the settings look like:
=> feat: SFTP directory file list steps 

tests/application_trait.php, tests/tool_dataflows_reader_csv_test.php
- test: avoid using class variables in this test to avoid mem leaks
- test: use https mock url by default
Totara test results:
```
...............................................................  63 / 324 ( 19%)
............................................................... 126 / 324 ( 38%)
............................................................... 189 / 324 ( 58%)
............................................................... 252 / 324 ( 77%)
.....................................S......................... 315 / 324 ( 97%)
.........                                                       324 / 324 (100%)
```
Resolves #823
=> fix totara unit tests

classes/dataflow.php
=> fix: loghandlers now optional and saving an existing flow should work

classes/local/execution/engine.php, classes/local/step/reader_csv.php, lang/en/tool_dataflows.php, version.php
Add message to make the error more actionable and include context in question
Resolves #842
After:
Before:
=> fix: error handling for when array_combine would fail

classes/local/step/set_variable_trait.php
- reduces noise (some flows might attempt to update the same value over and over)
- step being entered into will still display as expected.
=> fix: set_variable step to only update when changed

classes/form/step_form.php, classes/local/execution/engine.php, classes/local/step/connector_set_multiple_variables.php, classes/local/step/connector_sql.php, classes/local/step/copy_file_trait.php, classes/local/step/flow_email.php, classes/local/step/flow_set_multiple_variables.php, classes/local/step/reader_csv.php, classes/local/step/set_multiple_variables_trait.php, classes/local/step/sftp_trait.php, classes/local/step/sql_trait.php, lang/en/tool_dataflows.php, lib.php, run.php, version.php
- feat: add connector SQL step
- fix: allow values to be corrected in bad states
- feat: add set multiple variables step type
- fix: warning logs now display and are more legible
- fix: add copy file error handling for directory creation
- feat: run name and id are now available as expressable vars
- fix: SQL trait handling of integer values and improve error message
- fix: update email flow step to support it as a final step
- fix: reader csv error to be more correct for header/fields count alignment
- fix: include row number in csv reader error
- perf: cache sftp object per identity to speed up subsequent actions
- feat: add an option to continue processing the csv file on known parse issues
For the SFTP one in particular, it was doing about 200ms initial connection time, 600-700ms …
=> additional goodies csv sftp perf sql and more

.github/workflows/ci.yml, README.md, version.php
Hi @keevan,
This PR fixes issue #853, 2 commits have been cherry-picked.
Regards,
Marc-A
=> Moodle 401 stable 853 historyfix

tests/tool_dataflows_connector_compression_test.php, tests/tool_dataflows_flow_compression_test.php
Before:
```
There were 3 failures:
1) tool_dataflows\tool_dataflows_connector_compression_test::test_gzip_compression_decompression
Property 'basedir' defined in 'tool_dataflows\tool_dataflows_connector_compression_test' was not reset after the test!
Please either find a way to avoid using a class variable or make sure it get's unset in the tearDown method to avoid creating memory leaks.
/var/www/site/server/lib/phpunit/classes/testcase.php:623
/var/www/sit/server/lib/phpunit/classes/testcase.php:148
2) tool_dataflows\tool_dataflows_connector_compression_test::test_gzip_validation
Property 'basedir' defined in 'tool_dataflows\tool_dataflows_connector_compression_test' was not reset after the test!
Please either find a way to avoid using a class variable or make sure it get's unset in the …
```
=> Unset class vars in test teardown

classes/external/trigger_dataflow.php
Closes #884 
From my testing, the ways to address this was either to use core_external\external_api (4.2+ only) or require externallib.
This is most likely only an issue when this class is called from the external api test, but requiring externallib.php shouldn't cause any harm and should work for both 4.1 and 4.2+.
I believe #796 has been resolved by https://github.com/catalyst/moodle-tool_dataflows/commit/87cf066716af3ced7ec022dbb0d827afd5adfa6d so we shouldn't need #803 
Side note - can we add this test to CI?
=> External API test fix #884

thirdpartylibs.xml
**Description:** This adds the missing Symfony libraries as mentioned in Issue #895:
* vendor/symfony/event-dispatcher-contracts
* vendor/symfony/cache-contracts
=> Issue #895: Add missing symfony libraries to thirdpartylibs.xml

classes/local/step/reader_sql.php, classes/local/step/sql_trait.php
Closes #911 
**Summary**
It was `clean_param` being called when `PARAM_TEXT` that mangles the `<=` in the sql. I checked a similar plugin report_customsql, and it used PARAM_RAW
**Testing**
- Manually tested by putting in the SQL from the issue linked above into step definitions, saved, and confirmed no longer removes the text after the `<=`
- (side note, I attempted to add a unit test for this which appears possible https://moodledev.io/docs/4.5/apis/subsystems/form#unit-testing but I could not get it to work properly and it does not seem worth it to spend any longer)
** Cherry picks**
- https://github.com/catalyst/moodle-tool_dataflows/pull/913
=> [#911] fix sql cleaning

.github/workflows/ci.yml, classes/local/step/connector_sns_notify.php, classes/local/step/s3_trait.php, lang/en/tool_dataflows.php, tests/tool_dataflows_test.php
We use marked for deprecation method, but HQ may change their mind about that. See some comms in https://tracker.moodle.org/browse/MDL-82459
=> issue #931: get rid of local_aws
